version: '3.8'

# Development-only docker-compose configuration
# Use with: docker-compose -f docker-compose.dev.yml up

services:
  # PostgreSQL for development
  postgres:
    image: postgres:15-alpine
    container_name: gate-postgres-dev
    environment:
      - POSTGRES_USER=gateadmin
      - POSTGRES_PASSWORD=localdev
      - POSTGRES_DB=gate_access_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gateadmin"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Adminer for database management
  adminer:
    image: adminer
    container_name: gate-adminer
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres

volumes:
  postgres_dev_data: