"""Add timezone field to system_settings

Revision ID: 16231ac537d8
Revises: c04e67e10eba
Create Date: 2025-10-29 23:17:50.733081

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16231ac537d8"
down_revision: str | None = "c04e67e10eba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "system_settings",
        sa.Column(
            "timezone",
            sa.String(length=100),
            nullable=True,
            comment="Timezone for displaying dates and times (IANA timezone identifier)",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("system_settings", "timezone")
    # ### end Alembic commands ###
