"""add_rate_limiting_to_access_links

Revision ID: 7c09b4a3f048
Revises: a8329ee07286
Create Date: 2025-10-28 20:53:52.231275

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c09b4a3f048"
down_revision: str | None = "a8329ee07286"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "access_links",
        sa.Column(
            "last_accessed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp of the last successful access for rate limiting",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("access_links", "last_accessed_at")
    # ### end Alembic commands ###
