"""Add system_settings table for webhook configuration

Revision ID: bd0a2bccf221
Revises: 5696b40b021b
Create Date: 2025-10-22 07:04:49.260555

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd0a2bccf221"
down_revision: str | None = "5696b40b021b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_settings",
        sa.Column(
            "webhook_url", sa.Text(), nullable=True, comment="URL to send gate open requests to"
        ),
        sa.Column(
            "webhook_token",
            sa.String(length=500),
            nullable=True,
            comment="Bearer token for webhook authentication",
        ),
        sa.Column(
            "webhook_timeout", sa.Integer(), nullable=False, comment="Webhook timeout in seconds"
        ),
        sa.Column(
            "webhook_retries",
            sa.Integer(),
            nullable=False,
            comment="Number of webhook retry attempts",
        ),
        sa.Column(
            "gate_open_duration_seconds",
            sa.Integer(),
            nullable=False,
            comment="Duration to keep gate open in seconds",
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("system_settings")
    # ### end Alembic commands ###
