"""Add link_cooldown_seconds to system_settings

Revision ID: bd357bf7a8d8
Revises: 7c09b4a3f048
Create Date: 2025-10-28 21:36:05.088029

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd357bf7a8d8"
down_revision: str | None = "7c09b4a3f048"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "system_settings",
        sa.Column(
            "link_cooldown_seconds",
            sa.Integer(),
            nullable=False,
            server_default="60",
            comment="Cooldown time in seconds before a link can be used again",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("system_settings", "link_cooldown_seconds")
    # ### end Alembic commands ###
